export const PRODUCTS = [
  { 
    id: 1, 
    name: "ATRINEC-SP Tablets",       
    slug: "atrinec-sp-tablets",
    image: "/products/ATRINEC-SP Tablets.png", 
    category: "Tablets", 
    description: "Advanced pain management and anti-inflammatory formulation.",
    composition: "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg",
    detailedDescription: "ATRINEC-SP is a powerful triple-action combination medicine used for the effective relief of pain, inflammation, and swelling in various musculoskeletal and joint conditions. It works by blocking the release of certain chemical messengers in the brain that cause pain and inflammation, while promoting tissue repair and reducing swelling.",
    benefits: ["Rapid pain relief", "Reduces inflammation and swelling", "Promotes faster healing", "Well-tolerated gastrointestinal profile"],
    usage: "Take one tablet twice daily after meals, or as directed by the physician. Do not crush or chew."
  },
  { 
    id: 2, 
    name: "Atrizyme Syrup",            
    slug: "atrizyme-syrup",
    image: "/products/Atrizyme Syrup.png", 
    category: "Syrups", 
    description: "Digestive enzyme supplement for improved gut health.",
    composition: "Fungal Diastase (1:1200) 50mg + Pepsin (1:3000) 10mg / 5ml",
    detailedDescription: "Atrizyme Syrup provides a balanced combination of digestive enzymes to treat indigestion, flatulence, and loss of appetite. It helps in the breakdown of complex carbohydrates and proteins into simpler forms, facilitating better nutrient absorption and alleviating digestive discomfort.",
    benefits: ["Improves digestion", "Relieves bloating and gas", "Stimulates healthy appetite", "Supports nutrient absorption"],
    usage: "Take 1-2 teaspoonfuls (5-10ml) immediately after meals, twice daily."
  },
  { 
    id: 3, 
    name: "IBGUT Sachet",              
    slug: "ibgut-sachet",
    image: "/products/IBGUT Sachet.png", 
    category: "Sachets", 
    description: "Probiotic formulation to restore intestinal flora balance.",
    composition: "Pre & Probiotic blend (Saccharomyces boulardii, Lactobacillus rhamnosus, Bifidobacterium longum) + Zinc",
    detailedDescription: "IBGUT Sachet contains a clinically proven blend of beneficial probiotic strains alongside prebiotic fibers and essential minerals. It is specifically designed to restore the natural balance of gut bacteria disrupted by antibiotics or intestinal infections, effectively managing diarrhea and promoting overall digestive immunity.",
    benefits: ["Restores gut microbiome", "Helps manage antibiotic-associated diarrhea", "Boosts local intestinal immunity", "Supports healthy digestion"],
    usage: "Mix the contents of one sachet in a glass of water or milk. Consume immediately. Take 1-2 sachets daily as advised."
  },
  { 
    id: 4, 
    name: "IBGUT Capsules",            
    slug: "ibgut-capsules",
    image: "/products/IBGUT-Capsules.png", 
    category: "Capsules", 
    description: "Daily probiotic support for optimal digestive wellness.",
    composition: "Pre & Probiotic blend (Saccharomyces boulardii, Lactobacillus rhamnosus, Bifidobacterium longum) + Fructooligosaccharides",
    detailedDescription: "IBGUT Capsules offer a convenient daily dose of highly resilient probiotic strains designed to survive stomach acid and colonize the intestinal tract. It helps maintain a healthy balance of microflora, supporting regular bowel movements and reducing symptoms of irritable bowel syndrome (IBS).",
    benefits: ["Maintains daily gut health", "Alleviates IBS symptoms", "Enhances nutrient absorption", "Supports immune system function"],
    usage: "Take one capsule daily before or after a meal, or as prescribed."
  },
  { 
    id: 14, 
    name: "Vitalyca Capsules",            
    slug: "vitalyca-capsules",
    image: "/products/Vitalyca-Capsules.png", 
    category: "Capsules", 
    description: "Multivitamin and antioxidant softgel capsules for overall health and vitality support.",
    composition: "Multivitamins, Multiminerals, and Antioxidants",
    detailedDescription: "Vitalyca Capsules provide a comprehensive blend of essential vitamins, minerals, and antioxidants in an easy-to-swallow softgel format. Formulated to combat daily stress, boost immunity, and support cellular health, these capsules are perfect for maintaining optimal vitality and addressing nutritional deficiencies.",
    benefits: ["Boosts daily energy levels", "Strengthens immune system", "Provides potent antioxidant protection", "Supports overall health and wellness"],
    usage: "Take one capsule daily after a meal, or as directed by your healthcare professional."
  },
  { 
    id: 5, 
    name: "Smadryl Syrup",             
    slug: "smadryl-syrup",
    image: "/products/Smadryl Syrup.png", 
    category: "Syrups", 
    description: "Effective cough suppressant and expectorant combination.",
    composition: "Diphenhydramine HCl 14.08mg + Ammonium Chloride 138mg + Sodium Citrate 57.03mg / 5ml",
    detailedDescription: "Smadryl Syrup is a trusted formulation for the symptomatic relief of dry and productive coughs associated with allergies, colds, or respiratory tract infections. It works by suppressing the cough reflex, thinning mucus to make it easier to cough up, and providing a soothing effect on irritated throat tissues.",
    benefits: ["Relieves both dry and wet cough", "Reduces throat irritation", "Acts as an effective expectorant", "Provides fast, soothing relief"],
    usage: "Adults: 2 teaspoonfuls (10ml) 3-4 times a day. Children: 1 teaspoonful (5ml) 3-4 times a day."
  },
  { 
    id: 6, 
    name: "SMAFER-D Protein Powder",   
    slug: "smafer-d-protein-powder",
    image: "/products/SMAFER-D Protein Powder.png", 
    category: "Nutritional", 
    description: "Comprehensive nutritional supplement for pregnant and lactating mothers.",
    composition: "High Quality Whey Protein + DHA + Essential Vitamins and Minerals",
    detailedDescription: "SMAFER-D Protein Powder is an advanced nutritional formula specifically designed to meet the increased demands of pregnancy and lactation. Enriched with Docosahexaenoic Acid (DHA) for fetal brain development, along with high-quality protein and essential micronutrients, it supports optimal maternal health and healthy infant growth.",
    benefits: ["Supports fetal brain and eye development", "Provides high-quality digestible protein", "Helps prevent maternal anemia", "Boosts energy and immunity"],
    usage: "Add 2-3 scoops (approx. 30g) to a glass of lukewarm milk or water. Stir well and consume immediately, twice daily."
  },
  { 
    id: 7, 
    name: "Smafer-XT Tablets",         
    slug: "smafer-xt-tablets",
    image: "/products/Smafer-XT Tablets.png", 
    category: "Tablets", 
    description: "Advanced iron and folic acid supplement for anemia management.",
    composition: "Ferrous Ascorbate (eq. to elemental iron 100mg) + Folic Acid 1.5mg + Zinc 22.5mg",
    detailedDescription: "Smafer-XT is a highly absorbable iron supplement formulated to effectively treat and prevent iron deficiency anemia. The inclusion of Ferrous Ascorbate ensures maximum iron absorption with minimal gastric irritation, while Folic Acid and Zinc support red blood cell formation and overall immune health.",
    benefits: ["Highly bioavailable form of iron", "Minimal gastrointestinal side effects", "Supports healthy RBC production", "Helps combat fatigue and weakness"],
    usage: "Take one tablet daily after a meal with a glass of water, or as directed by your physician."
  },
  { 
    id: 8, 
    name: "Smakast-L Suspension",      
    slug: "smakast-l-suspension",
    image: "/products/Smakast-L Suspension.png", 
    category: "Syrups", 
    description: "Pediatric anti-allergic and anti-asthmatic suspension.",
    composition: "Levocetirizine Dihydrochloride 2.5mg + Montelukast Sodium 4mg / 5ml",
    detailedDescription: "Smakast-L Suspension offers a dual-action approach to managing allergic rhinitis and asthma in children. Levocetirizine acts as a potent antihistamine to relieve sneezing and runny nose, while Montelukast serves as a leukotriene receptor antagonist to reduce airway inflammation and prevent asthma attacks.",
    benefits: ["Effective 24-hour allergy relief", "Reduces airway inflammation", "Non-sedating formula", "Pleasant taste for high pediatric compliance"],
    usage: "Children (2-5 years): 2.5ml once daily in the evening. Children (6-14 years): 5ml once daily in the evening."
  },
  { 
    id: 9, 
    name: "Smamox CV 625 Tablets",     
    slug: "smamox-cv-625-tablets",
    image: "/products/Smamox CV 625 Tablets.png", 
    category: "Tablets", 
    description: "Broad-spectrum antibiotic combination for tough bacterial infections.",
    composition: "Amoxycillin 500mg + Potassium Clavulanate 125mg",
    detailedDescription: "Smamox CV 625 is a powerful broad-spectrum antibiotic used to treat a wide variety of bacterial infections, including respiratory tract, ear, sinus, skin, and urinary tract infections. The addition of Potassium Clavulanate protects Amoxycillin from degradation by beta-lactamase enzymes produced by resistant bacteria, ensuring maximum efficacy.",
    benefits: ["Effective against resistant bacterial strains", "Broad-spectrum coverage", "High clinical success rate", "Convenient oral dosage"],
    usage: "Take one tablet every 8-12 hours depending on the severity of the infection, exactly as prescribed by your doctor."
  },
  { 
    id: 10, 
    name: "Smapime-250 Injection",    
    slug: "smapime-250-injection",
    image: "/products/Smapime-250 Injection.png", 
    category: "Injections", 
    description: "Fourth-generation cephalosporin for severe hospital-acquired infections.",
    composition: "Cefepime 250mg (For IM/IV use)",
    detailedDescription: "Smapime-250 is a potent injectable antibiotic reserved for the treatment of moderate to severe bacterial infections, including pneumonia, urinary tract infections, and skin infections. As a fourth-generation cephalosporin, it exhibits excellent activity against both Gram-positive and Gram-negative organisms, making it critical for empirical therapy in serious settings.",
    benefits: ["Potent bactericidal action", "Broad coverage including Pseudomonas", "Highly effective for severe infections", "Suitable for pediatric and adult use"],
    usage: "To be administered only by a healthcare professional via intramuscular or intravenous route."
  },
  { 
    id: 11, 
    name: "Tripam-LS Tablets",        
    slug: "tripam-ls-tablets",
    image: "/products/Tripam-LS Tablets.png", 
    category: "Tablets", 
    description: "Anxiolytic and antidepressant combination for mood disorders.",
    composition: "Clonazepam 0.25mg + Escitalopram Oxalate 5mg",
    detailedDescription: "Tripam-LS combines the rapid anxiolytic effects of Clonazepam with the sustained mood-elevating properties of Escitalopram. It is specifically formulated for the treatment of comorbid anxiety and depressive disorders, helping patients achieve emotional stability and improved quality of life while minimizing side effects.",
    benefits: ["Rapid relief from anxiety symptoms", "Long-term improvement in mood", "Balanced formulation for better tolerability", "Improves sleep patterns associated with anxiety"],
    usage: "Take one tablet daily, preferably at the same time each day, strictly as prescribed by a psychiatrist."
  },
  { 
    id: 12, 
    name: "Tripam-Plus Tablets",      
    slug: "tripam-plus-tablets",
    image: "/products/Tripam-Plus Tablets.png", 
    category: "Tablets", 
    description: "Higher strength anxiolytic combination for severe cases.",
    composition: "Clonazepam 0.5mg + Escitalopram Oxalate 10mg",
    detailedDescription: "Tripam-Plus is an advanced strength formulation designed for patients requiring more robust intervention for severe anxiety disorders, panic attacks, or major depressive episodes. It provides comprehensive regulation of neurotransmitters in the brain to restore mental calm and emotional balance.",
    benefits: ["Effective for severe panic disorders", "Potent mood stabilizer", "Comprehensive neurotransmitter regulation", "Reduces frequency of anxiety attacks"],
    usage: "Take one tablet daily, strictly under medical supervision. Do not discontinue abruptly."
  },
  { 
    id: 13, 
    name: "Vitalyca Suspension",      
    slug: "vitalyca-suspension",
    image: "/products/Vitalyca Suspension.png", 
    category: "Syrups", 
    description: "Complete multivitamin and mineral tonic for daily vitality.",
    composition: "Multivitamins, Multiminerals, and Antioxidants with L-Lysine",
    detailedDescription: "Vitalyca Suspension is a comprehensive daily tonic designed to bridge nutritional gaps, boost immunity, and promote overall vitality. Enriched with essential vitamins, minerals, and L-Lysine to enhance appetite, it is ideal for individuals recovering from illness, growing children, and those experiencing general weakness.",
    benefits: ["Boosts energy and reduces fatigue", "Strengthens immune defense", "Promotes healthy growth and development", "Contains antioxidants to fight cellular stress"],
    usage: "Adults: 10ml twice daily. Children: 5ml once or twice daily, or as directed by the physician."
  }
];
